export { LoginPage } from './LoginPage'
export { RegisterPage } from './RegisterPage'
export { DashboardPage } from './DashboardPage'
export { UploadPage } from './UploadPage'
export { ResultsPage } from './ResultsPage'
export { GoalDetailPage } from './GoalDetailPage'
export { ComparePage } from './ComparePage'
