#!/usr/bin/env python3
"""Generate static SDG target definitions from the Excel source.

One-time script: reads data/external/SDG_TargetX_v1/sdg_targetx_v1.xlsx,
deduplicates targets, and writes src/config/sdg_target_definitions.py as a
static Python dict. Run again only if the Excel source changes.

Usage:
    python scripts/generate_target_definitions.py
"""

import sys
from pathlib import Path

import pandas as pd

XLSX_PATH = Path("data/external/SDG_TargetX_v1/sdg_targetx_v1.xlsx")
OUTPUT_PATH = Path("src/config/sdg_target_definitions.py")
COLUMNS = ["sdg_id", "sdg_goal", "target_id", "target_text",
           "target_layman_description", "detailed_info"]


def main():
    if not XLSX_PATH.exists():
        print(f"ERROR: {XLSX_PATH} not found")
        sys.exit(1)

    df = pd.read_excel(XLSX_PATH, usecols=COLUMNS)
    print(f"Loaded {len(df)} rows from {XLSX_PATH}")

    # Drop nulls in essential columns
    df = df.dropna(subset=["target_text", "target_layman_description", "detailed_info"])
    print(f"After dropping nulls: {len(df)} rows")

    # Deduplicate by (sdg_id, target_id), keep first occurrence
    before = len(df)
    df = df.drop_duplicates(subset=["sdg_id", "target_id"], keep="first")
    print(f"Deduplicated: {before} -> {len(df)} rows (removed {before - len(df)} duplicates)")

    # Sort by sdg_id then target_id
    df = df.sort_values(["sdg_id", "target_id"]).reset_index(drop=True)

    # Build the dict
    target_defs = {}
    for _, row in df.iterrows():
        key = str(row["target_id"])
        target_defs[key] = {
            "sdg_num": int(row["sdg_id"]),
            "target_id": str(row["target_id"]),
            "target_text": str(row["target_text"]),
            "layman_description": str(row["target_layman_description"]),
            "detailed_info": str(row["detailed_info"]),
        }

    # Write the Python file
    lines = [
        '"""UN SDG Target Definitions.',
        "",
        "Auto-generated by scripts/generate_target_definitions.py.",
        "Do not edit manually — re-run the script if the source Excel changes.",
        '"""',
        "",
        "from typing import Dict, List, Any",
        "",
        "",
        f"SDG_TARGET_DEFINITIONS: Dict[str, Dict[str, Any]] = {{",
    ]

    for key, val in target_defs.items():
        # Escape quotes in strings
        tt = val["target_text"].replace("\\", "\\\\").replace('"', '\\"')
        lay = val["layman_description"].replace("\\", "\\\\").replace('"', '\\"')
        det = val["detailed_info"].replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'    "{key}": {{')
        lines.append(f'        "sdg_num": {val["sdg_num"]},')
        lines.append(f'        "target_id": "{val["target_id"]}",')
        lines.append(f'        "target_text": "{tt}",')
        lines.append(f'        "layman_description": "{lay}",')
        lines.append(f'        "detailed_info": "{det}",')
        lines.append("    },")

    lines.append("}")
    lines.append("")
    lines.append("")
    lines.append("def get_targets_for_sdg(sdg_num: int) -> Dict[str, Dict[str, Any]]:")
    lines.append('    """Return all targets for a given SDG number."""')
    lines.append("    return {")
    lines.append("        tid: t for tid, t in SDG_TARGET_DEFINITIONS.items()")
    lines.append("        if t[\"sdg_num\"] == sdg_num")
    lines.append("    }")
    lines.append("")
    lines.append("")
    lines.append("def get_all_target_ids() -> List[str]:")
    lines.append('    """Return sorted list of all target IDs."""')
    lines.append("    return sorted(SDG_TARGET_DEFINITIONS.keys())")
    lines.append("")

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text("\n".join(lines))
    print(f"\nWrote {len(target_defs)} target definitions to {OUTPUT_PATH}")

    # Verify counts per SDG
    from collections import Counter
    counts = Counter(v["sdg_num"] for v in target_defs.values())
    print("\nTargets per SDG:")
    for sdg in sorted(counts.keys()):
        print(f"  SDG {sdg:2d}: {counts[sdg]}")


if __name__ == "__main__":
    main()