# SDG-specific ensemble weights
# Auto-generated by scripts/analysis/sync_threshold_config.py
# Format: {sdg_number: (sdg_bert_weight, st_weight)}
# weight = precision / (st_precision + sdgbert_precision)

SDG_ENSEMBLE_WEIGHTS = {
    1: (0.516, 0.484),
    2: (0.527, 0.473),
    3: (0.518, 0.482),
    4: (0.566, 0.434),
    5: (0.499, 0.501),
    6: (0.514, 0.486),
    7: (0.503, 0.497),
    8: (0.728, 0.272),
    9: (0.571, 0.429),
    10: (0.643, 0.357),
    11: (0.638, 0.362),
    12: (0.599, 0.401),
    13: (0.494, 0.506),
    14: (0.526, 0.474),
    15: (0.505, 0.495),
    16: (0.631, 0.369),
    17: (0.689, 0.311),
}

DEFAULT_SDG_BERT_WEIGHT = 0.50
DEFAULT_ST_WEIGHT = 0.50
